- hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Add key for docker repo
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Install docker-ce
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Allow docker to log to syslog
      copy:
        src: ./daemon.json
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: 0600

    - name: Restart and enable docker
      service:
        name: docker
        state: restarted
        enabled: yes




